name: Testing Pull Request
on:
  push: null
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install black
      run: 'pip install black[jupyter]==24.4.2

        '
    - name: Run black formatter on PyDMD source code
      run: "black --check --diff --color pydmd/ utils/ tests/\nif [[ $? -ne \"0\" ]]; then\n  echo \"\
        Source code needs re-formatting\"\n  exit 1\nfi\n"
    - name: Run black formatter on PyDMD tutorials
      run: "black --check --diff --color tutorials/\nif [[ $? -ne \"0\" ]]; then\n  echo \"Tutorials need\
        \ re-formatting\"\n  exit 1\nfi\n"
  sort_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install isort
      run: 'pip install isort

        '
    - name: Run isort on PyDMD source code
      run: "OUT=$(isort pydmd/ tests/)\nif [[ $OUT ]]; then\n    echo \"All imports are properly sorted\"\
        \nelse\n    echo \"$OUT\"\nfi\n"
  unit_test:
    needs: prepare_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJson(needs.prepare_matrix.outputs.matrix_unit_test) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install Python dependencies
      run: 'pip install .[test]

        # Force NumPy version

        pip install numpy==${{ matrix.numpy-version }}

        '
    - name: Test with pytest
      run: 'pytest

        '
  tutorial_test:
    needs: prepare_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJson(needs.prepare_matrix.outputs.matrix_tutorial_test) }}
      fail-fast: false
    env:
      TUTORIAL_TIMEOUT: 1200s
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: 'pip install .[test]

        # Dependencies for tutorials

        pip install jupyter pandas opencv-python ffmpeg-python

        # Force NumPy version

        pip install numpy==${{ matrix.numpy-version }}

        # timeout not available by default on MacOS

        brew install coreutils || true

        '
    - uses: actions/cache@v2
      id: cache-segtrackv2
      with:
        path: ./tutorials/tutorial12/SegTrackv2
        key: SegTrackv2-key
    - name: Download SegTrackv2
      if: steps.cache-segtrackv2.outputs.cache-hit != 'true'
      run: 'curl https://web.engr.oregonstate.edu/~lif/SegTrack2/SegTrackv2.zip --output SegTrackv2.zip

        unzip -qq SegTrackv2.zip

        mv SegTrackv2 tutorials/tutorial12

        '
    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3.1
    - name: Check tutorial references
      run: "cd tutorials/\nfor dir in $(ls -d tutorial*/); do\n  if grep -q \"$dir\" \"README.md\"\n \
        \   then\n    echo \"$dir is referenced\"\n  else\n    echo \"$dir not referenced\"\n    exit\
        \ 1\n  fi\ndone\n"
    - name: Test tutorials
      run: "set -x\ncd tutorials/\nfor dir in $(ls -d tutorial*/); do\n  if [[ $dir != tutorial5* ]]\n\
        \    then\n    cd $dir\n    timeout --signal=SIGKILL $TUTORIAL_TIMEOUT python -Xfrozen_modules=off\
        \ -m jupyter nbconvert --to notebook --execute *.ipynb\n    cd ..\n  fi\ndone\nset +x\n"
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_unit_test: ${{ steps.setmatrix.outputs.matrix1 }}
      matrix_tutorial_test: ${{ steps.setmatrix.outputs.matrix2 }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Set Dynamic Matrix
      id: setmatrix
      run: 'matrix_str=$(python utils/info2json.py testing_matrix)

        echo "matrix1=$matrix_str" >> $GITHUB_OUTPUT

        matrix_str=$(python utils/info2json.py tutorial_testing_matrix)

        echo "matrix2=$matrix_str" >> $GITHUB_OUTPUT

        '
    - name: Install json2yaml
      run: 'sudo npm install -g json2yaml

        '
    - name: Check matrix definition
      run: 'matrix=''${{ steps.setmatrix.outputs.matrix1 }}''

        echo $matrix

        echo $matrix | jq .

        echo $matrix | json2yaml

        '
